#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso thermophysicalModels/combustionModels
wclean libso thermophysicalModels/radiation/submodels/absorptionEmissionModel
wclean libso thermophysicalModels/radiation/derivedFvPatchFields
wclean libso fvPatchFields
wclean libso fvPatchFieldsPyrolysis
wclean libso regionCoupling
wclean libso regionModels/pyrolysisModels

# ----------------------------------------------------------------- end-of-file
