#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

./installVersion.sh

touch fireFoam.C

wmake

# ----------------------------------------------------------------- end-of-file
